### ISSUE TITLE
您好，请教个问题

### ISSUE THREAD

**Issue by johnson-xu01** [jsksxs360/Word2Vec#1]
请问您的计算句子相似度的算法是什么？

**Comment by jsksxs360** [comment]
![eb6152c7869f5360bbe8c62ddbef0783](https://cloud.githubusercontent.com/assets/12483392/23738578/cfb2be8e-04d4-11e7-8b88-cfda9a61861f.png)

**Comment by johnson-xu01** [comment]
really thank you. 请问这是什么论文和书籍，可以介绍参考一下吗，谢谢。

**Comment by jsksxs360** [comment]
哦，这个来自于徐帅的论文[《面向问答系统的复述识别技术研究与实现》](http://xueshu.baidu.com/s?wd=%E9%9D%A2%E5%90%91%E9%97%AE%E7%AD%94%E7%B3%BB%E7%BB%9F%E7%9A%84%E5%A4%8D%E8%BF%B0%E8%AF%86%E5%88%AB%E6%8A%80%E6%9C%AF%E7%A0%94%E7%A9%B6%E4%B8%8E%E5%AE%9E%E7%8E%B0)

**Comment by cugdeeplearn** [comment]
你好，请问，在进行测试的过程中，狗|猫: 0.0
计算机|电脑: 0.0
计算机|人: 0.0
请问是什么原因呢？ 模型是用的网上别人训练好的。谢谢

**Comment by jsksxs360** [comment]
你好，

这跟你使用的模型有关。你使用的可能不是用google代码训练出来的。所以没有加载成功。

不好意思，回复地比较晚。

发自我的 iPhone

**Comment by gembin** [comment]
@jsksxs360 请问还有哪些句子相似度的算法？ 或者比较好的算法？

**Comment by jsksxs360** [comment]
@gembin 不好意思，这方面没做过具体的研究。其实本身句子相似度用 w2v 来计算就不是很合理，最好还是能直接对句子建模，直接从句子层级来计算。

**Comment by gembin** [comment]
多谢！
