### ISSUE TITLE
关于里面的loadModel变量

### ISSUE THREAD

**Issue by lijian2033** [jsksxs360/Word2Vec#2]
Word2Vec中的loadModel变量在public void loadGoogleModel(String modelPath)中设置的为true，但是在public void loadJavaModel(String modelPath)中设置为true，在训练好后的java模型中，然后加载public void loadJavaModel(String modelPath)的方法，会导致null，作者你看一下是否是变量设置为false的原因

**Comment by jsksxs360** [comment]
你好，这个问题已修复，非常感谢你的提醒。确实是 `loadJavaModel` 方法里把 `loadModel` 变量的值赋错了，自己一直都是用 Google 的模型，所以一直没有发现这个问题。

> 目前只在源代码中做了修正，新的发布版本会在积累更多更新后编译。
