### ISSUE TITLE
句子相似度计算方法出处

### ISSUE THREAD

**Issue by guozhaotong** [jsksxs360/Word2Vec#5]
您好！请问计算句子相似度的`fastSentenceSimilarity()`和`sentenceSimilarity()`，两个方法是参考了什么文献呢？

**Comment by jsksxs360** [comment]
你好!

`sentenceSimilarity()` 实现了 2009 徐帅[《面向问答系统的复述识别技术研究与实现》](http://xueshu.baidu.com/s?wd=%E9%9D%A2%E5%90%91%E9%97%AE%E7%AD%94%E7%B3%BB%E7%BB%9F%E7%9A%84%E5%A4%8D%E8%BF%B0%E8%AF%86%E5%88%AB%E6%8A%80%E6%9C%AF%E7%A0%94%E7%A9%B6%E4%B8%8E%E5%AE%9E%E7%8E%B0) 中的句子相似度计算方法：

![1](https://user-images.githubusercontent.com/12483392/40096412-54de3bdc-5903-11e8-8053-0b51c20e776b.png)

在 2017 [《基于主题相似度的宏观篇章主次关系识别方法》](http://xueshu.baidu.com/s?wd=%E5%9F%BA%E4%BA%8E%E4%B8%BB%E9%A2%98%E7%9B%B8%E4%BC%BC%E5%BA%A6%E7%9A%84%E5%AE%8F%E8%A7%82%E7%AF%87%E7%AB%A0%E4%B8%BB%E6%AC%A1%E5%85%B3%E7%B3%BB%E8%AF%86%E5%88%AB%E6%96%B9%E6%B3%95)中，蒋峰等人也使用了该计算方法提取特征。

`fastSentenceSimilarity()` 只是简单地将句子中词语向量的叠加（按位加）作为句子的表示向量，然后直接计算句子向量之间的 Cosine 值。理论依据，可以参见苏剑林[《更别致的词向量模型(五)：有趣的结果》](https://kexue.fm/archives/4677#%E5%8F%A5%E5%AD%90%E7%9A%84%E7%9B%B8%E4%BC%BC%E5%BA%A6)。
