### ISSUE TITLE
请问这个可不可以适用于英文

### ISSUE THREAD

**Issue by PetePro** [jsksxs360/Word2Vec#9]
请问这个可不可以适用于英文，英文的使用跟中文类似吗，有没有推荐的英文语料库供训练
[抱拳]

**Comment by jsksxs360** [comment]
你好，可以的。Word2Vec 是一个语言模型，本身和语言类型无关。只要有分好词的语料，都可以训练的。

**Comment by PetePro** [comment]
> 你好，可以的。Word2Vec 是一个语言模型，本身和语言类型无关。只要有分好词的语料，都可以训练的。

训练也和中文的使用方法一样对吗？
另外，请问你知道有什么英文语料可以用的~

**Comment by jsksxs360** [comment]
你好，训练方法和中文一样的，在分好词的语料上进行训练。

英语的话，建议可以直接使用 Google 训练好的模型： [GoogleNews-vectors-negative300.bin.gz](https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit)，相关信息可以参考 [word2vec 说明页](https://code.google.com/archive/p/word2vec/)。

英文语料建议使用维基百科，可以参考 [word2vec 说明页](https://code.google.com/archive/p/word2vec/)中的 **Where to obtain the training data**

英语分词可以使用[斯坦福 NLP 处理包](https://stanfordnlp.github.io/stanfordnlp/)

**Comment by PetePro** [comment]
好的，谢谢你！

**Comment by PetePro** [comment]
再次请教一下：
我照着中文的样子使用Google训练好的模型：
`Word2Vec vec = new Word2Vec();
try {
	vec.loadGoogleModel("D:\\WorkSpace\\EclipseJee\\GoogleNews-vectors-negative300.bin");
} catch (IOException e) {
	e.printStackTrace();
}
Set<WordEntry> similarWords = vec.getSimilarWords("hello", 10);
for (WordEntry word : similarWords) {
	System.out.println(word.name + " : " + word.score);
}`
运行过后报这样的错：Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded。我谷歌查了，是因为耗尽了所有可用内存。
请问你知道有什么解决办法吗？

**Comment by cvenwu** [comment]
> 再次请教一下：
> 我照着中文的样子使用Google训练好的模型：
> `Word2Vec vec = new Word2Vec(); try { vec.loadGoogleModel("D:\\WorkSpace\\EclipseJee\\GoogleNews-vectors-negative300.bin"); } catch (IOException e) { e.printStackTrace(); } Set<WordEntry> similarWords = vec.getSimilarWords("hello", 10); for (WordEntry word : similarWords) { System.out.println(word.name + " : " + word.score); }`
> 运行过后报这样的错：Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded。我谷歌查了，是因为耗尽了所有可用内存。
> 请问你知道有什么解决办法吗？

这个应该是你的**内存不够**了吧，我加载的时候模型消耗了3G左右的内存

**Comment by PetePro** [comment]
> > 再次请教一下：
> > 我照着中文的样子使用Google训练好的模型：
> > `Word2Vec vec = new Word2Vec(); try { vec.loadGoogleModel("D:\\WorkSpace\\EclipseJee\\GoogleNews-vectors-negative300.bin"); } catch (IOException e) { e.printStackTrace(); } Set<WordEntry> similarWords = vec.getSimilarWords("hello", 10); for (WordEntry word : similarWords) { System.out.println(word.name + " : " + word.score); }`
> > 运行过后报这样的错：Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded。我谷歌查了，是因为耗尽了所有可用内存。
> > 请问你知道有什么解决办法吗？
> 
> 这个应该是你的**内存不够**了吧，我加载的时候模型消耗了3G左右的内存

请问你的电脑内存有多大？
